spring:
    application:
        name: MyWebApplication
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:./h2db/sandbox
        username: dev
        password: dev
logging:
    level:
        org.springframework.jdbc.core: DEBUG

